#!/bin/bash

conda install --channel=conda-forge python=3.7 pip hdf5=1.12.0 notebook
export HDF5_DIR=/srv/conda/envs/notebook
echo $HDF5_DIR

pip install git+https://github.com/h5py/h5py
pip install git+https://github.com/hdmf-dev/hdmf
pip install git+https://github.com/NeurodataWithoutBorders/pynwb
pip install nwbwidgets